feat: ['feature', 'feat']
fix: ['fix', 'bugfix', 'bug']
docs: ['doc', 'docs', 'documentation']
style: ['style']
refactor: ['refactor']
perf: ['perf', 'performance']
test: ['test', 'tests']
build: ['build', 'ci', 'cd']
chore: ['chore']
revert: ['revert']