version: "3"

includes:
  infisical:
    taskfile: ./taskfiles/infisical.yaml
  docker:
    taskfile: ./taskfiles/docker.yaml
  webapp:
    taskfile: ./workspaces/webapp
    dir: ./workspaces/webapp
  database:
    taskfile: ./workspaces/database
    dir: ./workspaces/database

tasks:
  # when you first want to spin up the project
  setup:
    - task: infisical:create-dotenv
    - task: clean
    - pnpm i
    - task: database:generate-prisma

  # Local development setup with Docker
  setup-local:
    desc: "Set up local development environment with Docker services"
    cmds:
      - ./scripts/setup-local-dev.sh

  # Start local development services
  dev-local:
    desc: "Start local development with Docker services"
    dotenv: [".env"]
    cmds:
      - docker-compose up -d
      - infisical run --env=dev -- pnpm turbo dev --parallel

  # Stop local development services
  stop-local:
    desc: "Stop local Docker services"
    cmds:
      - docker-compose down
  # build the prisma client. eventually we will get rid of this
  generate-prisma:
    - infisical run -- docker compose run --rm -it webapp pnpm run setup:db
  # spin up the dev
  dev:
    dotenv: [".env"]
    cmds:
      - task: docker:up-daemon
      - defer: task docker:down
      - pnpm turbo dev --parallel
  start:
    dotenv: [".env"]
    cmds:
      - task: docker:up-daemon
      - defer: task docker:down
      - pnpm turbo start --parallel
  clean:
    - rm -rf node_modules
    - task: webapp:clean
    - pnpm clean -r
  # cleanup and start from scratch
  from-scratch:
    - task: clean
    - pnpm install --verbose # needed for local IDE.
    - task: docker:down
    - task: setup
    - task: dev
  reset:
    - task: docker:down-and-cleanup
    - task: clean
