FROM node:20-bullseye-slim

# Install pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && corepack prepare pnpm@9.0.0 --activate

# Set working directory
WORKDIR /application

# Install dependencies
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY workspaces/websocket/package.json ./workspaces/websocket/
COPY workspaces/database/package.json ./workspaces/database/

# Install dependencies
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

# Set development environment
ENV NODE_ENV=development

# Expose port
EXPOSE 8080

# Command to run the application
CMD ["pnpm", "run", "--filter=@unique-chess/websocket", "dev"]